#!/bin/sh
set -eu

NV=$1
# ubuntu version
# sudo groupadd -g 7438 sandbox
# alpine version
addgroup -g 7438 sandbox

# ubuntu version
# sudo adduser --system --no-create-home --shell /bin/false -u 7438 -gid 7438 sandbox
# alpine version
adduser -S -H -s /bin/false -u 7438 -g sandbox -G sandbox sandbox
chown -R sandbox:sandbox ${PWD}

INIT=$(docker inspect -f "{{index .Config.Labels \"io.redsift.sandbox.install\" }}" $NV)
echo "Calling init = $INIT"
docker run -u 7438:7438 $NV-testing $INIT 0 2 3 && ls -A "/run/sandbox/sift/server/node_modules" "/run/sandbox/sift/server-alt/node_modules"

RUN=$(docker inspect -f "{{index .Config.Labels \"io.redsift.sandbox.run\" }}" $NV)
echo "Calling run = $RUN"
docker run -u 7438:7438 -v "${PWD}/test:/run/sandbox/sift:ro" -e DRY=true $NV-testing $RUN 0 2 3
