#!/bin/sh
set -eu

NV=$1
groupadd -g 7438 sandbox
adduser --system --no-create-home --shell /bin/false -u 7438 -gid 7438 sandbox
chown -R sandbox:sandbox ${PWD}

INIT=$(docker inspect -f "{{index .Config.Labels \"io.redsift.sandbox.install\" }}" $NV)
echo "Calling init = $INIT"
docker run -u 7438:7438 -v $PWD/test:/run/sandbox/sift $NV $INIT 0 2 3
ls -A $PWD/test/server/node_modules $PWD/test/server-alt/node_modules

RUN=$(docker inspect -f "{{index .Config.Labels \"io.redsift.sandbox.run\" }}" $NV)
echo "Calling run = $RUN"
docker run -u 7438:7438 -v $PWD/test:/run/sandbox/sift:ro -e DRY=true $NV $RUN 0 2 3
rm -Rf $PWD/test/server/node_modules $PWD/test/server-alt/node_modules