#!/bin/bash
set -eu

NV=$1
SUFFIX=${IS_RELEASE:-"-beta"}

VERSION=$(docker run -u 7438:7438 $NV --version)
V_TAG=$CONTAINER_NAME:$VERSION${SUFFIX/true/}
echo "Tagging as $V_TAG"
docker tag $NV $V_TAG

MAJOR_VERSION=(${VERSION//./ })
MV_TAG=$CONTAINER_NAME:$MAJOR_VERSION${SUFFIX/true/}
echo "Tagging as $MV_TAG"
docker tag $NV $MV_TAG

