#!/bin/bash
set -eu

NV=$1

cat << EOF > ./Dockerfile.testing
FROM ${NV}:latest
MAINTAINER Christos Vontas email: christos@redsift.io version: 1.0.1

COPY --chown=7438:7438 test /run/sandbox/sift
EOF

