#!/bin/bash
set -eu

NV=$1
CIRCLE_BRANCH=${CIRCLE_BRANCH/\//-} # fix/sth => fix-sth
tagName=(${CIRCLE_BRANCH/-/ }) # release-1 => release
SUFFIX="-beta"
if [ $tagName == "release" ]; then
  SUFFIX=""
fi
imageName=$CONTAINER_NAME:v$NV$SUFFIX

cat << EOF > ./Dockerfile.testing
FROM ${imageName}
MAINTAINER Christos Vontas email: christos@redsift.io version: 1.0.1

COPY --chown=7438:7438 test /run/sandbox/sift
EOF

