FROM quay.io/redsift/sandbox-javascript:latest
MAINTAINER Christos Vontas email: christos@redsift.io version: 1.0.1

COPY --chown=7438:7438 test /run/sandbox/sift

COPY root /tmp/root
COPY test /tmp/test
COPY package.json /tmp
COPY package-lock.json /tmp
COPY jsconfig.json /tmp

RUN cd /tmp && npm ci