version: 2.1

default:
  environment: &envvars
    CONTAINER_NAME: quay.io/redsift/sandbox-javascript
    CIRCLE_REVERSE_DEPENDENCIES: sandbox-dmarc-insights
executors:
  dockexec:
    shell: /bin/bash
    environment: *envvars
    docker:
      - image: cibuilds/docker:18.06.3-ce

  baseexec:
    shell: /bin/bash
    environment: *envvars
    docker:
      - image: cibuilds/base:2019.03


commands:
  v_build:
    parameters:
      nv:
        type: string
        default: "8.10.0"
      islatest:
        type: boolean
        default: false
    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u $QUAY_USER -p $QUAY_PASS quay.io
      - run: echo Building << parameters.nv >>
      - run: docker build --build-arg nodev=<< parameters.nv >> -t << parameters.nv >> .
      - run: ./circleci/gen_testing_dockerfile << parameters.nv >>
      - run: docker build -t << parameters.nv >>-testing -f Dockerfile.testing .
      - run: ./circleci/docker_test << parameters.nv >>
      - run: ./circleci/docker_tagging << parameters.nv >> << parameters.islatest >>

jobs:
  build:
    executor: dockexec
    steps:
      - v_build:
          nv: "8.10.0"

  build_8.15:
    executor: dockexec
    steps:
      - v_build:
          nv: "8.15.0"
          islatest: true

  trigger-builds:
    executor: baseexec
    steps:
      - checkout
      - run: ./circle_ci_trigger_build

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build
      - build_8.15
      - trigger-builds:
          requires:
            - build
          filters:
            branches:
              only:
                - master
