version: 2.1

default:
  environment: &envvars
    CONTAINER_NAME: quay.io/redsift/sandbox-javascript
    CIRCLE_REVERSE_DEPENDENCIES: sandbox-dmarc-insights
executors:
  dockexec:
    shell: /bin/bash
    environment: *envvars
    docker:
      - image: cibuilds/docker:18.06.3-ce

  baseexec:
    shell: /bin/bash
    environment: *envvars
    docker:
      - image: cibuilds/base:2019.03


commands:
  v_build:
    parameters:
      nv:
        type: string
        default: "8.10.0"
      islatest:
        type: boolean
        default: false
    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u $QUAY_USER -p $QUAY_PASS quay.io
      - run: echo Building << parameters.nv >>
      - run: docker build --build-arg nodev=<< parameters.nv >> -t << parameters.nv >> .
      - run: ./circleci/gen_testing_dockerfile << parameters.nv >>
      - run: docker build -t << parameters.nv >>-testing -f Dockerfile.testing .
      - run: ./circleci/docker_test << parameters.nv >>
      - run: ./circleci/docker_tagging << parameters.nv >>
      - when:
          condition: << parameters.islatest >>
          steps:
            - run: echo "Tagging as $CONTAINER_NAME:latest"
            - run: docker tag << parameters.nv >> $CONTAINER_NAME:latest

jobs:
  build:
    parallelism: 2
    executor: dockexec
    steps:
      - v_build:
          nv: "8.15.1"
      - v_build:
          nv: "8.10.0"

  build-release:
    executor: dockexec
    environment:
      IS_RELEASE: true
    steps:
      - v_build:
          nv: "8.15.1"
          islatest: true
      - v_build:
          nv: "8.10.0"

  trigger-builds:
    executor: baseexec
    steps:
      - checkout
      - run: ./circle_ci_trigger_build

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - /release-.*/
      - trigger-builds:
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - build-release:
          filters:
            branches:
              only:
                - /release-.*/
