#!/bin/bash
set -eu

NV=$1
IS_LATEST=${2:-}

CIRCLE_BRANCH=${CIRCLE_BRANCH/\//-} # fix/sth => fix-sth
tagName=(${CIRCLE_BRANCH/-/ }) # release-1 => release
SUFFIX="-beta"
if [ $tagName == "release" ]; then
  SUFFIX=""
fi
imageName=$CONTAINER_NAME:v$NV$SUFFIX

echo Building $imageName
docker build --build-arg nodev=$NV -t $imageName .

V=$(docker run -u 7438:7438 $imageName --version)
echo "Container reported version ${V}"

MAJOR_VERSION=(${NV//./ })
MV_TAG=$CONTAINER_NAME:v$MAJOR_VERSION$SUFFIX
echo "Tagging as $MV_TAG"
docker tag $imageName $MV_TAG

if [[ "$tagName" == "release" ]] && [[ "$IS_LATEST" == "true" ]]; then
  echo "Tagging as $CONTAINER_NAME:latest"
  docker tag $imageName $CONTAINER_NAME:latest
fi
