#!/bin/bash
set -eu

NV=$1
IS_LATEST=${2:-}

CIRCLE_BRANCH=${CIRCLE_BRANCH/\//-} # fix/sth => fix-sth
tagName=(${CIRCLE_BRANCH/-/ }) # release-1 => release
SUFFIX="-beta"
parentVersion="beta"
if [ $tagName == "release" ]; then
  SUFFIX=""
  parentVersion="latest"
fi

dockerInputfile="node8.Dockerfile"
if [ $NV == "10.17.0" ]; then
  dockerInputfile="node10.Dockerfile"
fi

imageName=$CONTAINER_NAME:v$NV$SUFFIX

echo "Configuring FROM in ${dockerInputfile} with base=sandbox:${parentVersion}"
sed "s/^\(FROM quay.io\/redsift\/sandbox:\).*$/\1${parentVersion}/" < $dockerInputfile > Dockerfile.versioned

echo Building $imageName
docker build --build-arg nodev=$NV -t $imageName -f Dockerfile.versioned .

V=$(docker run -u 7438:7438 $imageName --version)
echo "Container reported version ${V}"

MAJOR_VERSION=(${NV//./ })
MV_TAG=$CONTAINER_NAME:v$MAJOR_VERSION$SUFFIX
echo "Tagging as $MV_TAG"
docker tag $imageName $MV_TAG

if [[ "$tagName" == "release" ]] && [[ "$IS_LATEST" == "true" ]]; then
  echo "Tagging as $CONTAINER_NAME:latest"
  docker tag $imageName $CONTAINER_NAME:latest
fi
