#!/bin/bash
set -eu

NV=$1
CIRCLE_BRANCH=${CIRCLE_BRANCH/\//-} # fix/sth => fix-sth
tagName=(${CIRCLE_BRANCH/-/ }) # release-1 => release
SUFFIX="-beta"
if [ $tagName == "release" ]; then
  SUFFIX=""
fi
imageName=$CONTAINER_NAME:v$NV$SUFFIX

sed "s~^FROM quay.io/redsift/sandbox-javascript:.*$~FROM $imageName~" < Dockerfile.test.templ > Dockerfile.testing


